[package]
authors = ["Kornel Lesiński <kornel@geekhood.net>"]
categories = ["multimedia::images"]
description = "Smart filter to remove Floyd-Steinberg dithering from paletted images"
documentation = "https://docs.rs/undither"
homepage = "https://lib.rs/undither"
license = "AGPL-3.0+"
name = "undither"
readme = "README.md"
repository = "https://github.com/kornelski/undither.git"
version = "1.0.2"
edition = "2018"

[[bin]]
doc = false
name = "undither"
path = "src/bin.rs"
required-features = ["binary"]

[dependencies]
imgref = "1.4.0"
itertools = "0.8.2"
loop9 = "0.1.1"
rgb = "0.8.16"
vpsearch = "1.3.5"

[dependencies.lodepng]
optional = true
version = "2.5.0"

[features]
binary = ["lodepng"]
